<a href="https://colab.research.google.com/github/EduardoAcostaC/Simulacion-I/blob/main/GeneradorCongruencial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Generador Congruencial Lineal

El generador congruencial lineal es un algoritmo que produce una secuencia de números pseudoaleatorios.
Se define por la siguiente fórmula recursiva:

 $ X_{n+1} = (a * X_n + c) mod m $

Donde:

* **X_n** es el número actual de la secuencia.
* **X_(n+1)** es el siguiente número de la secuencia.
* **a** es el multiplicador.
* **c** es el incremento.
* **m** es el módulo.
* **X_0** es la semilla o valor inicial.

La calidad del generador depende de la elección de los parámetros a, c, m y X_0.
Un buen generador producirá una secuencia de números que parezca aleatoria y que tenga un ciclo de vida largo.

In [8]:
import pandas as pd
from IPython.display import display

# Parámetros del generador congruencial
a = 23   # Multiplicador
c = 67  # Incremento
m = 1000  # Módulo
x_0 = 15  # Semilla

# Funcion Generadora
def generador(a, c, m, x_0):
    """
    Genera un número pseudoaleatorio utilizando el método congruencial lineal.

    Args:
        a (int): Multiplicador.
        c (int): Incremento.
        m (int): Módulo.
        x_0 (int): Semilla.

    Returns:
        int: Número pseudoaleatorio generado.
    """
    x = (a * x_0 + c) % m
    return x

muestra = []
ciclo_vida = []  # Almacena la secuencia de números generados
se_repite = False  # Bandera para verificar si el generador se repite

# Bucle principal (iterar m veces o hasta que se repita)
for i in range(m):
    nuevo = generador(a, c, m, x_0)
    muestra.append([i, x_0, nuevo, nuevo / m])
    x_0 = nuevo
    ciclo_vida.append(x_0)

    # Verifica si el número ya se generó
    if x_0 in ciclo_vida[:-1]:
        se_repite = True
        print("Ciclo de vida del generador:", ciclo_vida[:i+1])
        print("El generador se repite en la iteración:", i + 1)
        break  # Detiene la generación si se repite

if not se_repite:
    print("El generador no se repite en el ciclo de vida.")

df = pd.DataFrame(muestra, columns=["Iteracion", "Xn", "X_n+1", "Xn/m"])
df_styled = df.style.set_properties(**{
    'background-color': 'lightblue',
    'color': 'black',
    'border-color': 'black',
    'border-width': '1px',
    'border-style': 'solid',
    'text-align': 'center'
})

display(df_styled)
print("Ciclo de vida del generador:", ciclo_vida)

Ciclo de vida del generador: [412, 543, 556, 855, 732, 903, 836, 295, 852, 663, 316, 335, 772, 823, 996, 975, 492, 383, 876, 215, 12, 343, 956, 55, 332, 703, 236, 495, 452, 463, 716, 535, 372, 623, 396, 175, 92, 183, 276, 415, 612, 143, 356, 255, 932, 503, 636, 695, 52, 263, 116, 735, 972, 423, 796, 375, 692, 983, 676, 615, 212, 943, 756, 455, 532, 303, 36, 895, 652, 63, 516, 935, 572, 223, 196, 575, 292, 783, 76, 815, 812, 743, 156, 655, 132, 103, 436, 95, 252, 863, 916, 135, 172, 23, 596, 775, 892, 583, 476, 15, 412]
El generador se repite en la iteración: 101

Ciclo de vida del generador: [412, 543, 556, 855, 732, 903, 836, 295, 852, 663, 316, 335, 772, 823, 996, 975, 492, 383, 876, 215, 12, 343, 956, 55, 332, 703, 236, 495, 452, 463, 716, 535, 372, 623, 396, 175, 92, 183, 276, 415, 612, 143, 356, 255, 932, 503, 636, 695, 52, 263, 116, 735, 972, 423, 796, 375, 692, 983, 676, 615, 212, 943, 756, 455, 532, 303, 36, 895, 652, 63, 516, 935, 572, 223, 196, 575, 292, 783, 76, 815, 812, 743, 156, 655, 132, 103, 436, 95, 252, 863, 916, 135, 172, 23, 596, 775, 892, 583, 476, 15, 412]